---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: full-lifecycle-sept30
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: full-lifecycle-sept30 
  name: full-lifecycle-sept30
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi