apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: full-lifecycle-sept30
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: full-lifecycle-sept30 
  name: full-lifecycle-sept30
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: full-lifecycle-sept30 
    weight: 100 
  wildcardPolicy: None
